export { default as Layout } from './Layout'
export { default as Navbar } from './Navbar'
export { default as Footer } from './Footer'
export { default as Hero } from './Hero'
export { default as BgAnim } from './BgAnim'
export { default as BtnMain } from './BtnMain'
export { default as Projects } from './Projects'
export { default as Technologies } from './Technologies'